<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>e714b04a-915a-457f-a92d-54181f980f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M6 7h12v2H6zm0 4h12v2H6zm0 4h6v2H6z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;layout-padding&quot;]/div[@class=&quot;ant-row ant-row-center&quot;]/div[@class=&quot;ant-col VaccineDetails_bodyCard__ScLdx&quot;]/div[@class=&quot;VaccineDetails_dataset_detail__0aXzU&quot;]/div[@class=&quot;VaccineDetails_datasetDetailData__Kkkcn&quot;]/form[1]/div[@class=&quot;VaccineDetails_family_member_list_container__-fBwL&quot;]/div[@class=&quot;VaccineDetails_family_member__container__2jEno&quot;]/label[1]/div[@class=&quot;VaccineDetails_family_member__data_container__vt6s6&quot;]/div[@class=&quot;VaccineDetails_family_member__data__action_container__86LMk&quot;]/div[@class=&quot;EditFamily_container__ykQk0&quot;]/button[@class=&quot;ant-btn ant-btn-default CustomButton_btn__I8aDc CustomButton_primary__c3-xI&quot;]/svg[1]/path[2]</value>
   </webElementProperties>
</WebElementEntity>
