<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Detail PendaftarNama LengkapKrishna ANI_30a89b</name>
   <tag></tag>
   <elementGuidId>e6281d75-6692-4a56-9173-e1a4c813b1be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-modal-wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/following::div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-modal-wrap</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail PendaftarNama LengkapKrishna ANIK161043872187702Tanggal Lahir04-02-2005Jenis KelaminLaki-LakiNomor Telepon08824122344Alamat RumahSentulJenis VaksinSinovacDosis keDosis 2Tanggal VaksinasiJumat, 22 Juli 2022Waktu07:00 - 15:00LokasiKlinik 1 Yonkes KostradSelesai</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ant-scrolling-effect&quot;]/div[4]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Haechann'])[1]/following::div[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Detail PendaftarNama LengkapKrishna ANIK161043872187702Tanggal Lahir04-02-2005Jenis KelaminLaki-LakiNomor Telepon08824122344Alamat RumahSentulJenis VaksinSinovacDosis keDosis 2Tanggal VaksinasiJumat, 22 Juli 2022Waktu07:00 - 15:00LokasiKlinik 1 Yonkes KostradSelesai' or . = 'Detail PendaftarNama LengkapKrishna ANIK161043872187702Tanggal Lahir04-02-2005Jenis KelaminLaki-LakiNomor Telepon08824122344Alamat RumahSentulJenis VaksinSinovacDosis keDosis 2Tanggal VaksinasiJumat, 22 Juli 2022Waktu07:00 - 15:00LokasiKlinik 1 Yonkes KostradSelesai')]</value>
   </webElementXpaths>
</WebElementEntity>
